### ISSUE TITLE
Use mirror of curse API

### ISSUE THREAD

**Issue by AlgorithmLX** [TerraFirmaCraft-The-Final-Frontier/FileDirector#17]
Hello! I propose to add the useCurseMirror clause in this [class](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/blob/master/mod-director-core/src/main/java/net/jan/moddirector/core/configuration/type/CurseRemoteMod.java#L103). Here's a view of it: `curseforge.com/api/v1/mods/${ProjectID}/files/${FileID}/download`.

The point is that not everyone has access to api.curse.tools. ([see my issue](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/issues/7))

**Comment by ACGaming** [comment]
As the official API requires an API key, this option is not considered for the time being.
