### ISSUE TITLE
URL encoding is missing

### ISSUE THREAD

**Issue by juraj-hrivnak** [TerraFirmaCraft-The-Final-Frontier/FileDirector#19]
URLs with a whitespace or a special character like `§` fail to download.
A proper URL encoding for URLs would be appreciated.

I can recommend [this library](https://github.com/ethauvin/urlencoder) (the JVM version of it).

**Comment by juraj-hrivnak** [comment]
Here is my log: https://mclo.gs/gm2ejws

**Comment by ACGaming** [comment]
Certainly not the nicest approach, but this works just fine:
```json
{
    "url": "https://mediafilez.forgecdn.net/files/2668/311/%C2%A7c%C2%A7lCream%20%C2%A77Cuisine%20Resource%20Pack%20-%200.5.0.zip",
	"folder": "resourcepacks"
}
```

**Comment by juraj-hrivnak** [comment]
Thanks. I tried this before and it did not work. Has anything changed since then?

**Comment by ACGaming** [comment]
Untouched for a longer time, tested with 1.8.3.

**Comment by juraj-hrivnak** [comment]
Okay, that works. I fixed it for [Pakku](https://github.com/juraj-hrivnak/Pakku/releases/tag/v0.15.1).
If this is ever gonna change, I hope it stays backwards compatible with the encoded URLs.

**Comment by juraj-hrivnak** [comment]
The problem is again that the encoded file names don't decode, so you end up with file names like this:
`%C2%A7c%C2%A7lCream%20%C2%A77Cuisine%20Resource%20Pack%20-%200.5.0.zip`
