### ISSUE TITLE
Upload to Modrinth

### ISSUE THREAD

**Issue by mczph** [TerraFirmaCraft-The-Final-Frontier/FileDirector#2]
some mods are All Rights Reserved and i can't include them in a Modrinth modpack,so i have to use ModDirector (now FileDirector) to download them.
by the way,can FileDirector download anti-third-party-download mods by curseforge ids?

**Comment by ACGaming** [comment]
Downloading of CurseForge mods abides by the CurseForge API, thus will only work with ‚exposed‘ mods. URL workarounds result in a 403 error and are most likely against their ToS anyway.
We can think about a Modrinth upload in the future!

**Comment by Lylythii** [comment]
I could be wrong but I believe mczph is requesting FileDirector be uploaded to Modrinth *itself*.
I meant to get around to this! Will do so now.

That said I was under the impression that Modrinth also allowed packaging with CurseForge mods? Guess not.

**Comment by mczph** [comment]
Yes,Modrinth allows packaging with CurseForge mods,but some mods need links back to their original page and some mods are not allowed(I don't know the exact rules).

**Comment by ACGaming** [comment]
@Lylythii Yes, that‘s what I was getting at as well. Glad this is a thing now!
