### ISSUE TITLE
Sometimes the "Checking installation..." window stays open indefinetely and leaves a java process open even when manually closed

### ISSUE THREAD

**Issue by phoenix-limited** [TerraFirmaCraft-The-Final-Frontier/FileDirector#21]
I'm a pack dev that uses this mod to download more mods and some resources. I've noticed that every about 10 or so launches, the window in the picture stays open indefinitely and leaves a java process open with usually about ~250mb ram usage and no cpu usage.
![Screenshot 2024-03-10 230522](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/assets/159532240/f579bdb4-1af5-4c5d-bb0e-c221c89f3c7f)
Curseforge even sees it and warns about minecraft already running. If I proceed anyway though, it does just fine. I couldn't see anything in the log, which I've attached, that indicates a problem. I also don't know if/don't see a log for the mod itself. I've linked the pack below for reference as well

https://www.curseforge.com/minecraft/modpacks/phoenixtech
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/files/14553080/latest.log)

**Comment by fortinator88** [comment]
how on earth did you get the icon working

**Comment by phoenix-limited** [comment]
> how on earth did you get the icon working

in the mod-director folder I have my logo.png with a size of 500x500, I doubt this matters unless your using a HiDPI screen like I am, still might not matter

and then I have a modpack.json file with this as the config

{
    "packName": "PhoenixTech",
    "icon": {
        "path": "config/mod-director/logo.png",
        "width": 64,
        "height": 64
   }
}

**Comment by fortinator88** [comment]
alright that worked, but the whole point was for me to have a picture that says all downloads are required and it only shows up after you click the download button

**Comment by phoenix-limited** [comment]
> alright that worked, but the whole point was for me to have a picture that says all downloads are required and it only shows up after you click the download button

It would be convenient to have an option to disable that function, or have a branch without it. My users always ask me if its real or not. I get it from a security standpoint, but still

**Comment by phoenix-limited** [comment]
> alright that worked, but the whole point was for me to have a picture that says all downloads are required and it only shows up after you click the download button

You could also downgrade to the version prior to the one introducing the agree window

**Comment by fortinator88** [comment]
is that really a thing? which version

**Comment by fortinator88** [comment]
i found the version but now it wont download anything it just says downloading forever
