### ISSUE TITLE
Reload crash

### ISSUE THREAD

**Issue by al-wei** [TerraFirmaCraft-The-Final-Frontier/FileDirector#25]
`{
    "folder": "mods",
    "fileName": "MoBends_1.12.2-1.2.1-19.12.21.jar",
    "disable": true
}`
`{
	"url": "https://gitee.com/fanrenla/mc-al/raw/master/mods/MoBends_1.12.2-1.2.1-19.12.21-alnl.jar"
},`

I disabled the mod, download the mod I mod.

The first time to start the game, that is, the first time to download the mod, successfully loaded. But the second time we started the game crash.

https://gist.github.com/al-wei/b7e5f4bad3b1bdd5aa0c6ec332067789

**Comment by ACGaming** [comment]
Please share your File Director config as well!

**Comment by al-wei** [comment]
> config

[mod-director.zip](https://github.com/user-attachments/files/15872158/mod-director.zip)

**Comment by al-wei** [comment]
> Please share your File Director config as well!

I offer you the modpack I'm working on.
I hope this helps, if it's a conflict issue.
[ALNL-test.zip](https://github.com/user-attachments/files/15872295/ALNL-test.zip)

**Comment by ACGaming** [comment]
Looks like another check needs to be implemented for the modify config type. Until then, you can use `"delete": true` instead of `"disable": true`.

**Comment by al-wei** [comment]
> Looks like another check needs to be implemented for the modify config type. Until then, you can use `"delete": true` instead of `"disable": true`.

OK
By the way, the mod-director in modpack was not given by me, it was old.
Because this is not a release.

**Comment by al-wei** [comment]
> Looks like another check needs to be implemented for the modify config type. Until then, you can use instead of .`"delete": true``"disable": true`

Rename crash
`{
    "modify": [
        {
            "folder": "mods",
            "fileName": "Resourcify (1.12.2-forge)-1.4.0.jar",
            "newFileName": "!!Resourcify (1.12.2-forge)-1.4.0.jar"
        },
        {
            "folder": "mods",
            "fileName": "MoBends_1.12.2-1.2.1-19.12.21.jar",
            "delete": true
        }
    ]
}`
https://gist.github.com/al-wei/bfad03a22bde3a1a3f9dd54a0ba61c04

**Comment by ACGaming** [comment]
Because of the new consent dialog which is enforced since 1.8.1, you can either mark Mo' Bends as an optional mod or let users disable the mod when first running the modpack if they so desire.

Downloading and disabling/deleting afterwards in the same launch is counter-intuitive and not planned as of now.
