### ISSUE TITLE
Window display

### ISSUE THREAD

**Issue by al-wei** [TerraFirmaCraft-The-Final-Frontier/FileDirector#26]
Did you know that it is usually displayed under the launcher so that the player cannot see it?
Most players don't think they can start the game.

If possible, the window should be at the top.
Or you can resize it and make it bigger.

![image](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/assets/145486869/0ba84072-cf79-419c-b690-da04e6b5c7dc)

**Comment by al-wei** [comment]
![image](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/assets/145486869/2fbe0b9b-3d07-40ba-b361-43dfc0401d22)
And there's no prompt on the taskbar.

**Comment by Krutoy242** [comment]
More and more players compain about this issue in E2EE issue tracker https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/401

When I could exect build with this fix to be released on CF?

**Comment by ACGaming** [comment]
1.9.0 is scheduled with Modrinth support and other fixes if applicable.
