### ISSUE TITLE
Rename crash

### ISSUE THREAD

**Issue by al-wei** [TerraFirmaCraft-The-Final-Frontier/FileDirector#27]
Rename crash

[mod-director](https://gist.github.com/al-wei/52f184239686fa9ea32157596176343a)

https://gist.github.com/al-wei/bfad03a22bde3a1a3f9dd54a0ba61c04

**Comment by ACGaming** [comment]
Can reproduce that files are locked before any renaming can apply, looking into it.

For now, you can directly rename files when downloading via URL:
```json
{
	"url": "https://cdn.modrinth.com/data/RLzHAoZe/versions/1jWOvZrk/Resourcify%20%281.12.2-forge%29-1.4.0.jar",
	"fileName": "!!Resourcify (1.12.2-forge)-1.4.0.jar"
}
```

**Comment by ACGaming** [comment]
As it turns out, Resourcify runs at coremod stage, so it's impossible to rename this particular mod, possibly other coremods as well. Since defining reliable loading orders at this stage is borderline impossible (at least with Forge), I can't do anything about it and you have to indeed refer to the workaround posted above.

**Comment by al-wei** [comment]
> As it turns out, Resourcify runs at coremod stage, so it's impossible to rename this particular mod, possibly other coremods as well. Since defining reliable loading orders at this stage is borderline impossible (at least with Forge), I can't do anything about it and you have to indeed refer to the workaround posted above.

I need to name the file because of Resourcify.
Because it contains kotlin, however, the Kotlin for Forge mod is too old and will cause the game to crash.

But I used Forgelin-Continuous, so I don't need to do that.

**Comment by ACGaming** [comment]
As stated, you can directly set the custom file name when downloading the file which is the cleanest approach for that matter.

**Comment by al-wei** [comment]
> As stated, you can directly set the custom file name when downloading the file which is the cleanest approach for that matter.

ok
