### ISSUE TITLE
Error opening remote hosted config

### ISSUE THREAD

**Issue by FranklinMCA** [TerraFirmaCraft-The-Final-Frontier/FileDirector#4]
Crash after launch, but every certificate valid on my host.
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/files/11179526/latest.log)

**Comment by ACGaming** [comment]
Please share your FileDirector config files, so I can try to reproduce.

**Comment by ACGaming** [comment]
Works fine on my end!
Please try to update to a more recent version of Java 8. Other than that, it is most likely related to your machine.

**Comment by ACGaming** [comment]
This can indeed be solved by using an up-to-date version of Java 8.

**Comment by FranklinMCA** [comment]
I used Tlauncher, which uses java 8 51
