### ISSUE TITLE
There is a way to specify if a mod client side or server side?

### ISSUE THREAD

**Issue by quentin452** [TerraFirmaCraft-The-Final-Frontier/FileDirector#8]
To only download the mod on server side or client side

**Comment by Lylythii** [comment]
Yup! Something like this should work.
```
{
	"curse":
	[
		{
			"addonId": 000000,
			"fileId": 000000,
			"metadata": {
				"side": "CLIENT"
			}
		}
	]
}
```

**Comment by quentin452** [comment]
and for an url by example?
i just need to do this?
{
    "url": "https://github.com/Scherso/NotSoEssential/releases/download/v1.0.3/NotSoEssential-Forge-1.0.3.jar",
    "side": "CLIENT"
}
